/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    pages: Page;
    posts: Post;
    categories: Category;
    medicalorders: Medicalorder;
    media: Media;
    users: User;
    medicalUsages: MedicalUsage;
    orders: Order;
    patients: Patient;
    MedicalRecods: MedicalRecod;
    suppliers: Supplier;
    medications: Medication;
    medicalSupplies: MedicalSupply;
    inventory: Inventory;
    inventorytransactions: Inventorytransaction;
    pharmacies: Pharmacy;
    appointments: Appointment;
    Rooms: Room;
    phieuxuat: Phieuxuat;
    departments: Department;
    class: Class;
    baogia: Baogia;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    patients: {
      benhan: 'appointments';
      hosobenhan: 'MedicalRecods';
    };
    MedicalRecods: {
      ylenh: 'medicalorders';
    };
    suppliers: {
      medications: 'medications';
      medicalsupplies: 'medicalSupplies';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    medicalorders: MedicalordersSelect<false> | MedicalordersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    medicalUsages: MedicalUsagesSelect<false> | MedicalUsagesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    patients: PatientsSelect<false> | PatientsSelect<true>;
    MedicalRecods: MedicalRecodsSelect<false> | MedicalRecodsSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    medications: MedicationsSelect<false> | MedicationsSelect<true>;
    medicalSupplies: MedicalSuppliesSelect<false> | MedicalSuppliesSelect<true>;
    inventory: InventorySelect<false> | InventorySelect<true>;
    inventorytransactions: InventorytransactionsSelect<false> | InventorytransactionsSelect<true>;
    pharmacies: PharmaciesSelect<false> | PharmaciesSelect<true>;
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    Rooms: RoomsSelect<false> | RoomsSelect<true>;
    phieuxuat: PhieuxuatSelect<false> | PhieuxuatSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    class: ClassSelect<false> | ClassSelect<true>;
    baogia: BaogiaSelect<false> | BaogiaSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hash?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  IDnhansu?: string | null;
  profilePicture?: (string | null) | Media;
  name?: string | null;
  cccd?: string | null;
  gioitinh?: ('nam' | 'nu' | 'khac') | null;
  ngaysinh?: string | null;
  sdt?: string | null;
  diachi?: string | null;
  notes?: string | null;
  chucvu?: ('bacsi' | 'yta' | 'kythuatvien' | 'letan' | 'truongphong' | 'truongkhoa' | 'duocsi' | 'khac') | null;
  vitri?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  khoa?: string | null;
  phong?: string | null;
  ngayvaolam?: string | null;
  tinhtranglamviec?: ('danglam' | 'nghiviec') | null;
  bangcap?: string | null;
  kinhnghiem?: number | null;
  chungchi?:
    | {
        tencc?: string | null;
        filecc?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medicalorders".
 */
export interface Medicalorder {
  id: string;
  hosobenhan?: (string | null) | MedicalRecod;
  khoa?: ('khoatai' | 'khoamui' | 'khoahong' | 'khoacapcuu' | 'khoagaymehoisuc' | 'khoaduoc') | null;
  bacsi?: (string | null) | User;
  dieuduong?: string | null;
  ngaynhapvien?: string | null;
  ngayLap?: string | null;
  chuandoan?: string | null;
  hinhthucdieutri?: ('benhnhannoitru' | 'benhnhanngoaitru') | null;
  thuoc?:
    | {
        thuocId?: string | null;
        hamLuong?: string | null;
        lieuDung?: string | null;
        cachDung?: string | null;
        thoiGian?: string | null;
        trangThai?: ('dangthuchien' | 'dacapphat') | null;
        id?: string | null;
      }[]
    | null;
  xetNghiem?:
    | {
        loaiXetNghiem?: string | null;
        moTa?: string | null;
        ngayChiDinh?: string | null;
        hinhAnh?: (string | null) | Media;
        fileDinhKem?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  ghichu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MedicalRecods".
 */
export interface MedicalRecod {
  id: string;
  tenBenhNhan?: string | null;
  thongtinbenhnhan?: (string | null) | Patient;
  hoso?:
    | {
        khoa?: (string | null) | Department;
        bacsi?: (string | null) | User;
        ngaynhapvien?: string | null;
        sophong?: string | null;
        chuandoan?: string | null;
        tomtat?: {
          lydo?: string | null;
          tomtat?: string | null;
          tiensu?: string | null;
          dienBienBenh?:
            | {
                ngay?: string | null;
                dienBien?: string | null;
                ghiChu?: string | null;
                id?: string | null;
              }[]
            | null;
          phuongphap?: ('dieutricanthiep' | 'dieutrihotro') | null;
          text?: string | null;
        };
        tinhtrang: 'yes' | 'no';
        tinhtrangxuatvien?: {
          ngayRaVien?: string | null;
          xuatvien?: ('khoi' | 'do' | 'khongthaydoi' | 'nang' | 'tuvong' | 'tienluongnang' | 'chuaxacdinh') | null;
          ghichu?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  ketqua?:
    | {
        infomation?: {
          ngay?: string | null;
          bacsi?: string | null;
          lydo?: {
            nghetmui?: boolean | null;
            dauhong?: boolean | null;
            chaymui?: boolean | null;
            utai?: boolean | null;
            khantieng?: boolean | null;
            kiemtrasaudieutri?: boolean | null;
            khac?: string | null;
          };
        };
        ketquanoisoi?:
          | (
              | {
                  binhthuong?: boolean | null;
                  viemtaingoai?: boolean | null;
                  viemtaigiua?: boolean | null;
                  khac?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'primaryhero';
                }
              | {
                  binhthuong?: boolean | null;
                  viemmuidiung?: boolean | null;
                  viemxoang?: boolean | null;
                  khac?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'secondaryHero';
                }
              | {
                  binhthuong?: boolean | null;
                  viehongcap?: boolean | null;
                  viemamidan?: boolean | null;
                  khantieng?: boolean | null;
                  tonthuong?: boolean | null;
                  khac?: string | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'Hero';
                }
            )[]
          | null;
        hinhanh?: (string | null) | Media;
        chandoan?: string | null;
        mucdo?: {
          binhthuong?: boolean | null;
          nhe?: boolean | null;
          trungbinh?: boolean | null;
          nang?: boolean | null;
          cantheodoithem?: boolean | null;
          khac?: string | null;
        };
        huongdieutri?: string | null;
        sosanh?: {
          caithien?: boolean | null;
          khongthaydoi?: boolean | null;
          tinhtrang?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  ylenh?: {
    docs?: (string | Medicalorder)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patients".
 */
export interface Patient {
  id: string;
  IDbenhnhan?: string | null;
  ten?: string | null;
  bhyt: 'co' | 'khong';
  idbaohiem?: string | null;
  cccd?: string | null;
  ngaysinh?: string | null;
  gioitinh?: ('nam' | 'nu' | 'khac') | null;
  nghenghiep?: string | null;
  diachi?: string | null;
  sdt?: string | null;
  email?: string | null;
  benhan?: {
    docs?: (string | Appointment)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  hosobenhan?: {
    docs?: (string | MedicalRecod)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  patients?: (string | null) | Patient;
  bacsi?: (string | null) | User;
  ngaykham?: string | null;
  giokham?: ('08:00' | '09:00' | '10:00' | '13:00' | '14:00' | '15:00') | null;
  trieuchung?: ('dau_hong' | 'nghet_mui' | 'chay_mau_cam' | 'u_tai' | 'khac')[] | null;
  yeucaudacbiet?: string | null;
  xacnhanthongtin?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: string;
  title?: string | null;
  tenkhoa?:
    | (
        | 'tai'
        | 'mui'
        | 'hong'
        | 'capcuu'
        | 'gaymehoisuc'
        | 'chandoanhinhanh'
        | 'khoaxetnghiem'
        | 'khoaduoc'
        | 'khoakhac'
      )
    | null;
  truongkhoa?: (string | User)[] | null;
  doctors?: (string | User)[] | null;
  nures?: (string | User)[] | null;
  thongtin?: {
    mota?: string | null;
    ngaythanhlap?: string | null;
  };
  departmentInventory?:
    | {
        category: 'medications' | 'vattutieuhao' | 'maymocthietbi';
        item?: (string | null) | Medication;
        items?: (string | null) | MedicalSupply;
        quantity?: number | null;
        unit?: string | null;
        expirydate?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medications".
 */
export interface Medication {
  id: string;
  medicationpicture?: (string | null) | Media;
  code?: string | null;
  name?: string | null;
  category?:
    | (
        | 'khangsinh'
        | 'giamdau'
        | 'huyetap'
        | 'tieuhoa'
        | 'taimuihong'
        | 'khangviem'
        | 'diung'
        | 'satkhuan'
        | 'xitmui'
        | 'siroho'
        | 'khac'
      )
    | null;
  unit?: ('pill' | 'bottle' | 'ampoule' | 'flask' | 'sachet' | 'box') | null;
  description?: string | null;
  dosage?: string | null;
  activeIngredient?: string | null;
  sideEffects?: string | null;
  contraindications?: string | null;
  supplier?: (string | Supplier)[] | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: string;
  nhacungcap?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  businessLicense?: string | null;
  businessLicenseFile?: (string | null) | Media;
  medications?: {
    docs?: (string | Medication)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  medicalsupplies?: {
    docs?: (string | MedicalSupply)[] | null;
    hasNextPage?: boolean | null;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medicalSupplies".
 */
export interface MedicalSupply {
  id: string;
  loaivattu?: ('vattutieuhao' | 'maymocthietbi') | null;
  code?: string | null;
  name?: string | null;
  category?:
    | (
        | 'dungchung'
        | 'phauthuat'
        | 'khukhuantiettrung'
        | 'chamsocvetthuong'
        | 'thietbichandoan'
        | 'dungcutiemvatruyendich'
        | 'vattuphongmo'
      )
    | null;
  description?: string | null;
  unit?: ('cai' | 'hop' | 'tui' | 'vi' | 'ong' | 'chai' | 'lit' | 'ml' | 'kg' | 'gram') | null;
  packaging?: string | null;
  manufacturer?: string | null;
  supplier?: (string | Supplier)[] | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medicalUsages".
 */
export interface MedicalUsage {
  id: string;
  usagedate?: string | null;
  department: string | Department;
  staff: string | User;
  items?:
    | {
        item?: (string | null) | MedicalSupply;
        quantity?: number | null;
        reason?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  customer: string | Patient;
  items?:
    | {
        medication: string | Medication;
        quantity?: number | null;
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  totalprice?: number | null;
  orderdate?: string | null;
  staff: string | User;
  paymentmethod: 'cash' | 'card' | 'insurance';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory".
 */
export interface Inventory {
  id: string;
  category: 'medications' | 'vattutieuhao' | 'maymocthietbi';
  item?: (string | null) | Medication;
  items?: (string | null) | MedicalSupply;
  sanpham?: string | null;
  quantity?: number | null;
  stockstatus: 'conhang' | 'hethang' | 'saphet' | 'hethansudung';
  reorderlevel?: number | null;
  supplier?: (string | Supplier)[] | null;
  importdate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventorytransactions".
 */
export interface Inventorytransaction {
  id: string;
  transactiondate?: string | null;
  giaodich?:
    | {
        nhacungcap?: (string | null) | Supplier;
        thoigian?: {
          gio?: number | null;
          phut?: number | null;
        };
        receiverorsender?: (string | null) | User;
        thuoc?:
          | {
              tenthuoc?: (string | null) | Medication;
              quantity?: number | null;
              donvi?: ('thung' | 'hop') | null;
              quychuan?: string | null;
              tongsohop?: number | null;
              unitprice?: string | null;
              totalprice?: string | null;
              id?: string | null;
            }[]
          | null;
        vattu?:
          | {
              tenvattu?: (string | null) | MedicalSupply;
              quantity?: number | null;
              donvi?: ('thung' | 'hop') | null;
              quychuan?: number | null;
              tongsohop?: number | null;
              unitprice?: string | null;
              totalprice?: string | null;
              id?: string | null;
            }[]
          | null;
        maymoc?:
          | {
              tenmaymoc?: (string | null) | MedicalSupply;
              quantity?: number | null;
              donvi?: ('cai' | 'bo') | null;
              unitprice?: string | null;
              totalprice?: string | null;
              id?: string | null;
            }[]
          | null;
        tongtien?: string | null;
        id?: string | null;
      }[]
    | null;
  tong_gia_tri_thuoc?: string | null;
  tong_gia_tri_vtth?: string | null;
  tong_gia_tri_mmtb?: string | null;
  tong_gia_tri?: string | null;
  report_notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pharmacies".
 */
export interface Pharmacy {
  id: string;
  category: 'medications' | 'vattutieuhao';
  item?: (string | null) | Medication;
  items?: (string | null) | MedicalSupply;
  sanpham?: string | null;
  quantity?: number | null;
  price?: number | null;
  unit?: string | null;
  expirydate?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Rooms".
 */
export interface Room {
  id: string;
  khoa: string | Department;
  totalRooms: number;
  Phong?:
    | {
        tenphongbenh?: (string | null) | MedicalRecod;
        totalBeds: number;
        benhnhan?: (string | Patient)[] | null;
        bsi?: (string | User)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phieuxuat".
 */
export interface Phieuxuat {
  id: string;
  transactiondate?: string | null;
  receiverorsender?: (string | null) | User;
  exports?:
    | {
        loai_xuat: 'khoa' | 'quaythuoc' | 'huy';
        destination?: (string | null) | Department;
        nguoinhan?: (string | null) | User;
        reason_cancel?: string | null;
        thuoc?:
          | {
              tenthuoc?: (string | null) | Medication;
              quantity?: number | null;
              donvi: 'hop' | 'thung';
              unitprice?: string | null;
              totalprice?: string | null;
              id?: string | null;
            }[]
          | null;
        vattutieuhao?:
          | {
              supply?: (string | null) | MedicalSupply;
              quantity?: number | null;
              donvi: 'hop' | 'thung';
              unitprice?: string | null;
              totalprice?: string | null;
              id?: string | null;
            }[]
          | null;
        maymocthietbi?:
          | {
              equipment?: (string | null) | MedicalSupply;
              quantity?: number | null;
              donvi: 'cai' | 'bo';
              unitprice?: string | null;
              totalprice?: string | null;
              id?: string | null;
            }[]
          | null;
        tongtien?: string | null;
        id?: string | null;
      }[]
    | null;
  tong_gia_tri_quaythuoc?: string | null;
  tong_gia_tri_khoa?: string | null;
  tong_gia_tri_huyhang?: string | null;
  tong_gia_tri?: string | null;
  report_notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class".
 */
export interface Class {
  id: string;
  tenphong?: ('hanhchinhquantri' | 'taichinhketoan' | 'anninh') | null;
  truongphong?: (string | User)[] | null;
  nhanvien?: (string | User)[] | null;
  thongtin?: {
    mota?: string | null;
    ngaythanhlap?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "baogia".
 */
export interface Baogia {
  id: string;
  category: 'medications' | 'medicalSupplies';
  item?: (string | null) | Medication;
  items?: (string | null) | MedicalSupply;
  sanpham?: string | null;
  gianhapnhacungcap?:
    | {
        nhacungcap?: (string | null) | Supplier;
        gianhap?: string | null;
        id?: string | null;
      }[]
    | null;
  gianhaptrungbinh?: string | null;
  thue?: number | null;
  loinhuan?: number | null;
  giaban?: string | null;
  donvi?: ('vien' | 'ong' | 'lo' | 'goi') | null;
  quychuan?: number | null;
  phantram?: number | null;
  tien?: string | null;
  donvis?: ('vien' | 'cuon' | 'mieng' | 'goi') | null;
  quychuans?: number | null;
  phantrams?: number | null;
  tiens?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'medicalorders';
        value: string | Medicalorder;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'medicalUsages';
        value: string | MedicalUsage;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'patients';
        value: string | Patient;
      } | null)
    | ({
        relationTo: 'MedicalRecods';
        value: string | MedicalRecod;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: string | Supplier;
      } | null)
    | ({
        relationTo: 'medications';
        value: string | Medication;
      } | null)
    | ({
        relationTo: 'medicalSupplies';
        value: string | MedicalSupply;
      } | null)
    | ({
        relationTo: 'inventory';
        value: string | Inventory;
      } | null)
    | ({
        relationTo: 'inventorytransactions';
        value: string | Inventorytransaction;
      } | null)
    | ({
        relationTo: 'pharmacies';
        value: string | Pharmacy;
      } | null)
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'Rooms';
        value: string | Room;
      } | null)
    | ({
        relationTo: 'phieuxuat';
        value: string | Phieuxuat;
      } | null)
    | ({
        relationTo: 'departments';
        value: string | Department;
      } | null)
    | ({
        relationTo: 'class';
        value: string | Class;
      } | null)
    | ({
        relationTo: 'baogia';
        value: string | Baogia;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: string | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medicalorders_select".
 */
export interface MedicalordersSelect<T extends boolean = true> {
  hosobenhan?: T;
  khoa?: T;
  bacsi?: T;
  dieuduong?: T;
  ngaynhapvien?: T;
  ngayLap?: T;
  chuandoan?: T;
  hinhthucdieutri?: T;
  thuoc?:
    | T
    | {
        thuocId?: T;
        hamLuong?: T;
        lieuDung?: T;
        cachDung?: T;
        thoiGian?: T;
        trangThai?: T;
        id?: T;
      };
  xetNghiem?:
    | T
    | {
        loaiXetNghiem?: T;
        moTa?: T;
        ngayChiDinh?: T;
        hinhAnh?: T;
        fileDinhKem?: T;
        id?: T;
      };
  ghichu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  hash?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  IDnhansu?: T;
  profilePicture?: T;
  name?: T;
  cccd?: T;
  gioitinh?: T;
  ngaysinh?: T;
  sdt?: T;
  diachi?: T;
  notes?: T;
  chucvu?: T;
  vitri?: T;
  khoa?: T;
  phong?: T;
  ngayvaolam?: T;
  tinhtranglamviec?: T;
  bangcap?: T;
  kinhnghiem?: T;
  chungchi?:
    | T
    | {
        tencc?: T;
        filecc?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medicalUsages_select".
 */
export interface MedicalUsagesSelect<T extends boolean = true> {
  usagedate?: T;
  department?: T;
  staff?: T;
  items?:
    | T
    | {
        item?: T;
        quantity?: T;
        reason?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customer?: T;
  items?:
    | T
    | {
        medication?: T;
        quantity?: T;
        price?: T;
        id?: T;
      };
  totalprice?: T;
  orderdate?: T;
  staff?: T;
  paymentmethod?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patients_select".
 */
export interface PatientsSelect<T extends boolean = true> {
  IDbenhnhan?: T;
  ten?: T;
  bhyt?: T;
  idbaohiem?: T;
  cccd?: T;
  ngaysinh?: T;
  gioitinh?: T;
  nghenghiep?: T;
  diachi?: T;
  sdt?: T;
  email?: T;
  benhan?: T;
  hosobenhan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MedicalRecods_select".
 */
export interface MedicalRecodsSelect<T extends boolean = true> {
  tenBenhNhan?: T;
  thongtinbenhnhan?: T;
  hoso?:
    | T
    | {
        khoa?: T;
        bacsi?: T;
        ngaynhapvien?: T;
        sophong?: T;
        chuandoan?: T;
        tomtat?:
          | T
          | {
              lydo?: T;
              tomtat?: T;
              tiensu?: T;
              dienBienBenh?:
                | T
                | {
                    ngay?: T;
                    dienBien?: T;
                    ghiChu?: T;
                    id?: T;
                  };
              phuongphap?: T;
              text?: T;
            };
        tinhtrang?: T;
        tinhtrangxuatvien?:
          | T
          | {
              ngayRaVien?: T;
              xuatvien?: T;
              ghichu?: T;
            };
        id?: T;
      };
  ketqua?:
    | T
    | {
        infomation?:
          | T
          | {
              ngay?: T;
              bacsi?: T;
              lydo?:
                | T
                | {
                    nghetmui?: T;
                    dauhong?: T;
                    chaymui?: T;
                    utai?: T;
                    khantieng?: T;
                    kiemtrasaudieutri?: T;
                    khac?: T;
                  };
            };
        ketquanoisoi?:
          | T
          | {
              primaryhero?:
                | T
                | {
                    binhthuong?: T;
                    viemtaingoai?: T;
                    viemtaigiua?: T;
                    khac?: T;
                    id?: T;
                    blockName?: T;
                  };
              secondaryHero?:
                | T
                | {
                    binhthuong?: T;
                    viemmuidiung?: T;
                    viemxoang?: T;
                    khac?: T;
                    id?: T;
                    blockName?: T;
                  };
              Hero?:
                | T
                | {
                    binhthuong?: T;
                    viehongcap?: T;
                    viemamidan?: T;
                    khantieng?: T;
                    tonthuong?: T;
                    khac?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        hinhanh?: T;
        chandoan?: T;
        mucdo?:
          | T
          | {
              binhthuong?: T;
              nhe?: T;
              trungbinh?: T;
              nang?: T;
              cantheodoithem?: T;
              khac?: T;
            };
        huongdieutri?: T;
        sosanh?:
          | T
          | {
              caithien?: T;
              khongthaydoi?: T;
              tinhtrang?: T;
            };
        id?: T;
      };
  ylenh?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  nhacungcap?: T;
  address?: T;
  phone?: T;
  email?: T;
  businessLicense?: T;
  businessLicenseFile?: T;
  medications?: T;
  medicalsupplies?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medications_select".
 */
export interface MedicationsSelect<T extends boolean = true> {
  medicationpicture?: T;
  code?: T;
  name?: T;
  category?: T;
  unit?: T;
  description?: T;
  dosage?: T;
  activeIngredient?: T;
  sideEffects?: T;
  contraindications?: T;
  supplier?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medicalSupplies_select".
 */
export interface MedicalSuppliesSelect<T extends boolean = true> {
  loaivattu?: T;
  code?: T;
  name?: T;
  category?: T;
  description?: T;
  unit?: T;
  packaging?: T;
  manufacturer?: T;
  supplier?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory_select".
 */
export interface InventorySelect<T extends boolean = true> {
  category?: T;
  item?: T;
  items?: T;
  sanpham?: T;
  quantity?: T;
  stockstatus?: T;
  reorderlevel?: T;
  supplier?: T;
  importdate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventorytransactions_select".
 */
export interface InventorytransactionsSelect<T extends boolean = true> {
  transactiondate?: T;
  giaodich?:
    | T
    | {
        nhacungcap?: T;
        thoigian?:
          | T
          | {
              gio?: T;
              phut?: T;
            };
        receiverorsender?: T;
        thuoc?:
          | T
          | {
              tenthuoc?: T;
              quantity?: T;
              donvi?: T;
              quychuan?: T;
              tongsohop?: T;
              unitprice?: T;
              totalprice?: T;
              id?: T;
            };
        vattu?:
          | T
          | {
              tenvattu?: T;
              quantity?: T;
              donvi?: T;
              quychuan?: T;
              tongsohop?: T;
              unitprice?: T;
              totalprice?: T;
              id?: T;
            };
        maymoc?:
          | T
          | {
              tenmaymoc?: T;
              quantity?: T;
              donvi?: T;
              unitprice?: T;
              totalprice?: T;
              id?: T;
            };
        tongtien?: T;
        id?: T;
      };
  tong_gia_tri_thuoc?: T;
  tong_gia_tri_vtth?: T;
  tong_gia_tri_mmtb?: T;
  tong_gia_tri?: T;
  report_notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pharmacies_select".
 */
export interface PharmaciesSelect<T extends boolean = true> {
  category?: T;
  item?: T;
  items?: T;
  sanpham?: T;
  quantity?: T;
  price?: T;
  unit?: T;
  expirydate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  patients?: T;
  bacsi?: T;
  ngaykham?: T;
  giokham?: T;
  trieuchung?: T;
  yeucaudacbiet?: T;
  xacnhanthongtin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  khoa?: T;
  totalRooms?: T;
  Phong?:
    | T
    | {
        tenphongbenh?: T;
        totalBeds?: T;
        benhnhan?: T;
        bsi?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phieuxuat_select".
 */
export interface PhieuxuatSelect<T extends boolean = true> {
  transactiondate?: T;
  receiverorsender?: T;
  exports?:
    | T
    | {
        loai_xuat?: T;
        destination?: T;
        nguoinhan?: T;
        reason_cancel?: T;
        thuoc?:
          | T
          | {
              tenthuoc?: T;
              quantity?: T;
              donvi?: T;
              unitprice?: T;
              totalprice?: T;
              id?: T;
            };
        vattutieuhao?:
          | T
          | {
              supply?: T;
              quantity?: T;
              donvi?: T;
              unitprice?: T;
              totalprice?: T;
              id?: T;
            };
        maymocthietbi?:
          | T
          | {
              equipment?: T;
              quantity?: T;
              donvi?: T;
              unitprice?: T;
              totalprice?: T;
              id?: T;
            };
        tongtien?: T;
        id?: T;
      };
  tong_gia_tri_quaythuoc?: T;
  tong_gia_tri_khoa?: T;
  tong_gia_tri_huyhang?: T;
  tong_gia_tri?: T;
  report_notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  title?: T;
  tenkhoa?: T;
  truongkhoa?: T;
  doctors?: T;
  nures?: T;
  thongtin?:
    | T
    | {
        mota?: T;
        ngaythanhlap?: T;
      };
  departmentInventory?:
    | T
    | {
        category?: T;
        item?: T;
        items?: T;
        quantity?: T;
        unit?: T;
        expirydate?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class_select".
 */
export interface ClassSelect<T extends boolean = true> {
  tenphong?: T;
  truongphong?: T;
  nhanvien?: T;
  thongtin?:
    | T
    | {
        mota?: T;
        ngaythanhlap?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "baogia_select".
 */
export interface BaogiaSelect<T extends boolean = true> {
  category?: T;
  item?: T;
  items?: T;
  sanpham?: T;
  gianhapnhacungcap?:
    | T
    | {
        nhacungcap?: T;
        gianhap?: T;
        id?: T;
      };
  gianhaptrungbinh?: T;
  thue?: T;
  loinhuan?: T;
  giaban?: T;
  donvi?: T;
  quychuan?: T;
  phantram?: T;
  tien?: T;
  donvis?: T;
  quychuans?: T;
  phantrams?: T;
  tiens?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        id?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}